from main import *


class NewProjectWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.resize(884, 520)
        self.centralwidget = QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(610, 115, 261, 331))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(610, 455, 81, 31))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 455, 81, 31))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(790, 455, 81, 31))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 15, 98, 31))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 886, 56))
        self.label.stackUnder(self.pushButton_4)
        font = QtGui.QFont("Arial")
        font.setPointSize(20)
        self.label.setFont(font)
        # self.label.setAutoFillBackground(True)
        self.label.setObjectName("label")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(485, 115, 101, 31))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 115, 461, 30))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 235, 126, 26))
        font = QtGui.QFont("Arial")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 305, 461, 30))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 340, 461, 30))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 75, 136, 31))
        font = QtGui.QFont("Arial")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(485, 150, 101, 31))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 150, 461, 30))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(470, 185, 116, 31))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_6 = QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(245, 185, 226, 30))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(470, 340, 116, 31))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(485, 270, 101, 31))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(485, 305, 101, 31))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 270, 226, 30))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(460, 390, 126, 26))
        font = QtGui.QFont("Arial")
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(499, 425, 86, 21))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(355, 425, 86, 21))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.lineEdit_10 = QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(445, 455, 141, 30))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(155, 425, 141, 21))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 425, 141, 21))
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.lineEdit_11 = QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(300, 455, 141, 30))
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 455, 141, 30))
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(155, 455, 141, 30))
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_8 = QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(245, 270, 226, 30))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(735, 75, 136, 31))
        font = QtGui.QFont("Arial")
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.setCentralWidget(self.centralwidget)
        self.setWindowTitle("مشروع جديد")
        ListItem = QListWidgetItem("المخزن الرئيسي")
        ListItem.setTextAlignment(QtCore.Qt.AlignCenter)
        self.listWidget.addItem(ListItem)
        self.listWidget.setCurrentItem(ListItem)
        self.pushButton.setText("حذف")
        self.pushButton_2.setText("تعديل")
        self.pushButton_3.setText("جديد")
        self.pushButton_4.setText("إنشاء المشروع")
        self.label.setText(" إعداد المشروع")
        self.label_2.setText("اسم المشروع")
        self.label_3.setText("بيانات الإتصال")
        self.label_4.setText("بيانات المشروع")
        self.label_5.setText("مجال العمل")
        self.label_6.setText("السجل الضريبي")
        self.label_7.setText("البريد الألكتروني")
        self.label_8.setText("أرقام الهاتف")
        self.label_9.setText("العنوان")
        self.label_10.setText("العملة")
        self.label_11.setText("اسم العملة")
        self.label_12.setText("تتكون من")
        self.label_13.setText("اسم العملة الصغري")
        self.label_14.setText("رمز العملة")
        self.lineEdit_11.setText("100")
        self.label_15.setText("اسماء المخازن")
        self.project_name_line = QLineEdit(self.centralwidget)
        self.project_name_line.hide()
        self.pushButton_4.clicked.connect(self.createProject)
        self.pushButton_3.clicked.connect(self.setStoreName)
        self.pushButton_2.clicked.connect(self.editStoreName)
        self.pushButton.clicked.connect(self.removeStore)
        self.show()

    def createProject(self):
        if self.lineEdit.text() == "":
            QMessageBox.information(self, "خطأ", "يجب تعين اسم للمشروع", QMessageBox.Ok)
            return 0
        if self.listWidget.count() == 0:
            QMessageBox.information(self, "خطأ", "يجب إضافة اسم مخزن للمشروع", QMessageBox.Ok)
            return 0
        if self.listWidget.count() == 0:
            QMessageBox.information(self, "خطأ", "يجب إضافة مخزن للمشروع", QMessageBox.Ok)
            return 0

    def setStoreName(self):
        listWidgetGeo = self.listWidget.geometry()
        listWidgetGeo.setHeight(LIST_WIDGET_HEIGHT)
        listWidgetGeo.adjust(0,LIST_WIDGET_HEIGHT*self.listWidget.count(),0,LIST_WIDGET_HEIGHT*self.listWidget.count())
        self.project_name_line.setText("")
        self.project_name_line.show()
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.project_name_line.setFont(font)
        self.project_name_line.setGeometry(listWidgetGeo)
        self.project_name_line.disconnect()
        self.project_name_line.returnPressed.connect(self.createStore)

    def editStoreName(self):
        if self.listWidget.count() == 0:
            return 0
        listWidgetGeo = self.listWidget.geometry()
        listWidgetGeo.setHeight(LIST_WIDGET_HEIGHT)
        listWidgetGeo.adjust(0,LIST_WIDGET_HEIGHT*self.listWidget.currentRow(),0,LIST_WIDGET_HEIGHT*self.listWidget.currentRow())
        self.project_name_line.setText("")
        self.project_name_line.show()
        font = QtGui.QFont("Arial")
        font.setPointSize(11)
        self.project_name_line.setFont(font)
        self.project_name_line.setGeometry(listWidgetGeo)
        self.project_name_line.disconnect()
        self.project_name_line.returnPressed.connect(self.editStore)

    def createStore(self):
        self.project_name_line.hide()
        if not self.project_name_line.text():
            return 0
        ListItem = QListWidgetItem(self.project_name_line.text())
        ListItem.setTextAlignment(QtCore.Qt.AlignCenter)
        self.listWidget.addItem(ListItem)
        if self.listWidget.count() == 1:
            self.listWidget.setCurrentItem(ListItem)

    def editStore(self):
        self.project_name_line.hide()
        if not self.project_name_line.text():
            return 0
        currentItem = self.listWidget.currentItem()
        currentItem.setText(self.project_name_line.text())

    def removeStore(self):
        self.listWidget.takeItem(
            self.listWidget.currentRow()
        )
        self.project_name_line.hide()


